run:
  concurrency: 4
  deadline: 1m
  issues-exit-code: 1
  tests: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  gofmt:
    simplify: true
  errcheck:
    check-type-assertions: true
    check-blank: false
  gocyclo:
    min-complexity: 10
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - govet
    - revive
    - gofmt
    - errcheck
    - misspell
    - gocyclo
    - ineffassign
    - goimports
    - nakedret
    - deadcode
    - prealloc
    - durationcheck
  fast: false